name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test C++ and Rust
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.8.5
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: bazelisk build //...
      - name: Test
        run: bazelisk test //...
