name: CI

on: [push, pull_request]

jobs:
  setup-bazel:
    name: Setup Bazel
    runs-on: ubuntu-latest

    steps:
      - uses: bazel-contrib/setup-bazel@0.8.5
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true

  cpp:
    name: C++
    runs-on: ubuntu-latest
    needs: setup-bazel
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: bazelisk build //cpp:all
      - name: Test
        run: bazelisk test //cpp:all

  rust:
    name: Rust
    runs-on: ubuntu-latest
    needs: setup-bazel
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: bazelisk build //rust:all
      - name: Test
        run: bazelisk test //rust:all
