name: CI

on: [push, pull_request]

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.8.5
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true
      - name: Checkout
        uses: actions/checkout@v4
      - name: C++
        run: bazelisk build //cpp:all
      - name: Rust
        run: bazelisk build //rust:all

  test-cpp:
    name: Test C++
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: bazelisk test //cpp:all

  test-rust:
    name: Test Rust
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: bazelisk test //rust:all
